### ISSUE TITLE
Question about boolean constraints

### ISSUE THREAD

**Issue by leilasamimi** [anb0s/YAFMT#29] opened 2018-10-06 21:43 UTC
Hi Mr. Andre Bossert,
I've installed and used YAFMT. Every thing is OK and the tool is very usable. However, I don't know how I can check the validity of the configuration model based on a defined constraint in the feature model. I have defined a constraint "A implies B". But in the configuration model, If A is selected and B is not selected, it does not show any error.
- Plugin version: **0.3.1**
- Eclipse Version: **2018-09 (4.9.0)**
- Java Version: **1.8**
- Operating System Version: **Windows**

**Comment by anb0s** [comment] 2018-10-06 22:06
Hi, thanks for using the tool ;)

I'm still using the original version 0.3.0 from forked project (by Jan Pikl) in production and it worked with constrains there. May be the new version >= 0.3.1 released by me has some regression about contrains. I will check it.

Anyway i will migrate to the version 0.4.0 soon and then see if constraints are working there...

**Comment by leilasamimi** [comment] 2018-10-07 18:48
Hi,
I updated the version of plugin based on the testing update site. It works well.
Now, I want to cite your tool in my paper. Is there any document (a technical report or article) for this tool?
Bests,
Leila.

**Comment by anb0s** [comment] 2018-10-07 19:09
Hi,
so the version 0.4.0 is working for you? 

The author of the original tool is Jan Pikl:
https://bitbucket.org/jpikl/
i've only found the Thesis about it in czech language:
https://otik.zcu.cz/bitstream/11025/7623/1/pikl-thesis.pdf
May be you can ask him about the thesis in english if available and other dociments.
The tool is documented here: https://bitbucket.org/jpikl/yafmt/wiki/Home

I've extended the tool for my needs, see my requests here: https://bitbucket.org/jpikl/yafmt/issues
I've moved the project to GitHub. I have no document about the extensions. You can cite info from the my project if you want. Please send me some info about your paper if available public :) Thanks!

Best,
Andre

P.S.: i'm also using FeatureIDE (https://featureide.github.io/) and EASy-Producer (https://sse.uni-hildesheim.de/en/research/projects/easy-producer/) for feature modeling in my projects...

**Comment by leilasamimi** [comment] 2018-10-10 12:26
Hi, 
Yes, the version 0.4.0 is OK. 
Thanks for the documents. I will cite your project website in the paper. If it will be accepted, I'll inform you.
Bests,
Leila.

**Comment by leilasamimi** [comment] 2018-10-10 15:53
Hi,
I want to write constraints on the attributes of features. But the attribute ID is not considered as a feature ID. The error says that "Nonexistent feature IDs: a_2388e90d_a69b_4e10_8afc_ef8fd9c478f9, a_16311fb0_bf75_4808_8762_d73f6741dfc8".
According to the carExample, if I want to define that Engine.Horsepower> 1000 implies Power Locks, what should I do? It seems the BoolCL does not support constraints on attributes. My attributes are all boolean not integer.

**Comment by anb0s** [comment] 2018-10-11 20:29
> It seems the BoolCL does not support constraints on attributes. My attributes are all boolean not integer.

You are right, it does not support constraints on attributes, see #2 i've wrote for the original v0.3.0

I need such constraints too and will try to implement them...

**Comment by anb0s** [comment] 2018-10-11 20:34
The feature contraints are working in general and therefore i want to close this issue if it's OK for you...
Please add your comments or your vote in the issue #2 Thanks!

**Comment by anb0s** [comment] 2019-01-09 09:02
close now, because of problem solved, please reopen if not, thanks!

**Closed as completed by anb0s** 2019-01-09 09:02 UTC
Labels: bug, regression, Version 0.3.1, investigation
